import { createServerFn } from "@tanstack/react-start";

// Pattern matches IDs generated by createBoldOrder: `MC-<ms-timestamp>-<8 hex>`
const ORDER_ID_RE = /^MC-\d{10,16}-[a-f0-9]{8}$/;
const ALLOWED_STATUS = new Set([
  "approved",
  "rejected",
  "pending",
  "failed",
  "unknown",
]);
const ALLOWED_CURRENCY = new Set(["USD", "COP"]);
// Mirrors the only values the checkout flow ever sends as a description.
const ALLOWED_DESCRIPTION = new Set([
  "masterclass-de-clientes-a-fans",
  "Masterclass: De clientes a fans",
  "Masterclass: De clientes a fans (50% OFF)",
  "Grabación Masterclass: De clientes a fans",
  "Grabación Masterclass: De clientes a fans (50% OFF)",
  "Grabación Masterclass: De clientes a fans + Kit de Ejecución",
]);

/**
 * Records a Bold payment outcome on the `orders` table.
 *
 * SECURITY: This is an unauthenticated server function called from the
 * post-checkout "gracias" page. To prevent arbitrary data injection into a
 * table that contains PII, we:
 *   - Only accept a tightly-validated `orderId` that matches the format we
 *     generate server-side in `createBoldOrder`.
 *   - Whitelist `status`, `currency`, and `description` to known values.
 *   - Cap `amount` to a safe integer range.
 *   - Never accept customer email / phone / name from the client. Those
 *     would only ever be authoritative from a Bold webhook, which is not
 *     wired up; storing client-supplied values here would let anyone seed
 *     fake PII against any order id.
 *   - Use idempotent upsert on `order_id` so repeated calls don't
 *     duplicate rows or let a caller flip an order's status repeatedly.
 */
export const recordOrder = createServerFn({ method: "POST" })
  .inputValidator(
    (data: {
      orderId?: string;
      status?: string;
      amount?: number;
      currency?: string;
      description?: string;
    }) => {
      const orderId = typeof data.orderId === "string" ? data.orderId : "";
      if (!ORDER_ID_RE.test(orderId)) {
        throw new Error("Invalid orderId");
      }

      const status = (data.status ?? "unknown").toLowerCase();
      if (!ALLOWED_STATUS.has(status)) {
        throw new Error("Invalid status");
      }

      let amount: number | null = null;
      if (data.amount !== undefined && data.amount !== null) {
        if (
          typeof data.amount !== "number" ||
          !Number.isFinite(data.amount) ||
          data.amount < 0 ||
          data.amount > 100_000_000
        ) {
          throw new Error("Invalid amount");
        }
        amount = Math.round(data.amount);
      }

      let currency: "USD" | "COP" | null = null;
      if (data.currency) {
        if (!ALLOWED_CURRENCY.has(data.currency)) {
          throw new Error("Invalid currency");
        }
        currency = data.currency as "USD" | "COP";
      }

      let description: string | null = null;
      if (data.description) {
        if (!ALLOWED_DESCRIPTION.has(data.description)) {
          throw new Error("Invalid description");
        }
        description = data.description;
      }

      return { orderId, status, amount, currency, description };
    },
  )
  .handler(async ({ data }) => {
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");

    const { data: existing } = await supabaseAdmin
      .from("orders")
      .select("id, status")
      .eq("order_id", data.orderId)
      .maybeSingle();

    if (existing) {
      // Only allow status to advance toward a terminal state. Anyone can
      // call this fn, so we refuse to flip an `approved` order back to
      // `pending` / `failed` etc.
      if (existing.status === "approved" && data.status !== "approved") {
        return { ok: true, id: existing.id, updated: false };
      }
      await supabaseAdmin
        .from("orders")
        .update({
          status: data.status,
          amount: data.amount,
          currency: data.currency,
        })
        .eq("id", existing.id);
      return { ok: true, id: existing.id, updated: true };
    }

    const { data: inserted, error } = await supabaseAdmin
      .from("orders")
      .insert({
        order_id: data.orderId,
        status: data.status,
        amount: data.amount,
        currency: data.currency,
        product: data.description ?? "masterclass-de-clientes-a-fans",
      })
      .select("id")
      .single();

    if (error) throw new Error(error.message);
    return { ok: true, id: inserted.id, updated: false };
  });
